export const EMOJI = {
  home: '🏡',
  studio: '⚡',
  editor: '🎨',
  lookbook: '📚',
  item: '🛍️',
  layers: '🧩',
  gallery: '🖼️',
  folder: '📁',
  grid: '🔳',
  download: '⬇️',
  upload: '📎',
  magic: '🪄',
  tools: '🛠️',
  ai: '🤖',
  compare: '⇆',
  eye: '👁️',
  hidden: '🙈',
  lock: '🔒',
  unlock: '🔓',
  warning: '⚠️',
  close: '✕',
  reset: '↺',
  swap: '↔️',
  clock: '⏳',
  check: '✓',
  spark: '✨',
  star: '✦',
  hair: '💇‍♀️',
  body: '📐',
  avatar: '👤',
  top: '👚',
  bottom: '👖',
  dress: '👗',
  shoes: '👠',
  bag: '👜',
  hat: '🧢',
  glasses: '🕶️',
  jewelry: '💍',
  outerwear: '🧥',
  starCircle: '🌟',
  sparkle: '✨',
  wave: '🌊',
  scissors: '✂️',
  crown: '👑',
  blackHeart: '🖤',
  sneaker: '👟',
  loafers: '🥿',
  sandals: '🩴',
  tote: '🛍️',
};

export type EmojiKey = keyof typeof EMOJI;

export function emojiOf(key: EmojiKey | string) {
  return (EMOJI as Record<string, string>)[key] ?? key;
}
